export const SET_ROUND_OF_16 = 'SET_ROUND_OF_16';
export const SET_ROUND_OF_8 = 'SET_ROUND_OF_8';
export const SET_SEMIFINALS = 'SET_SEMIFINALS';
export const SET_FINALS = 'SET_FINALS';
export const SET_MATCH_RESULT = 'SET_MATCH_RESULT';
export const SET_ROUND_MATCHES = 'SET_ROUND_MATCHES';
